import fs from "fs";
import path from "path";
import {
  buildSystemPrompt,
  TOPIC_IDS,
  DOC_CHUNKS,
} from "@chartroom/core";

// Plugin-specific tool descriptions (these are MCP tools, not shared with web)
const TOOL_DESCRIPTIONS = {
  load_csv:
    "Load and parse a CSV or Excel file. Returns column metadata (names, types, sample values). Supports .csv, .tsv, .xls, .xlsx.",
  validate_chart:
    "Validate a Vega-Lite spec against the compiler. Returns errors or warnings.",
  render_chart:
    "Render a Vega-Lite spec to a PNG image. Returns the file path of the saved image.",
  open_interactive:
    "Open the chart interactively in the user's default browser with hover tooltips and panning.",
} as const;

const SKILL_DIR = path.resolve(import.meta.dir, "../skills/chart");
const DOCS_DIR = path.join(SKILL_DIR, "docs");
const GENERATED_COMMENT = "<!-- Generated by bun run generate-skill — do not edit manually -->";

// --- Generate SKILL.md ---

const toolsSection = Object.entries(TOOL_DESCRIPTIONS)
  .map(([name, desc]) => `- **${name}** — ${desc}`)
  .join("\n");

const systemPrompt = buildSystemPrompt({ context: "plugin" });

// Topic list grouped by category (matching current SKILL.md structure)
const TOPIC_GROUPS: Record<string, string[]> = {
  "Mark types": ["bar", "line", "area", "point", "rect", "rule", "text", "tick", "arc", "boxplot"],
  "Encoding & scales": ["encoding", "color-scale", "position-scales", "styling"],
  "Transforms": ["aggregate", "stack", "fold", "filter", "calculate", "lookup"],
  "Composition": ["layer", "facet", "repeat", "concat"],
  "Patterns & checklists": ["layout-patterns", "composite-patterns", "editing-charts", "pre-render-checklist"],
};

const docsSection = Object.entries(TOPIC_GROUPS)
  .map(([group, topics]) => {
    const items = topics.map((t) => `\`${t}.md\``).join(", ");
    return `- **${group}**: ${items}`;
  })
  .join("\n");

const skillMd = `${GENERATED_COMMENT}
---
name: chart
description: Generate charts from CSV/Excel data using Vega-Lite. Use when the user wants to create, modify, or explore data visualizations from CSV or Excel files.
user-invocable: true
allowed-tools: Read, Bash(open *)
---

# Chart Generation Workflow

You have access to Chartroom MCP tools for creating Vega-Lite charts from CSV or Excel data.

## Available MCP Tools

${toolsSection}

${systemPrompt}

## Reference Documentation

Vega-Lite reference docs are in the \`docs/\` directory next to this file. Read the relevant doc **before** generating any spec.

**Available topics** (read the file matching your mark/transform):
${docsSection}

Example: to make a bar chart with aggregation, read \`docs/bar.md\` and \`docs/aggregate.md\` first.
`;

fs.mkdirSync(SKILL_DIR, { recursive: true });
fs.writeFileSync(path.join(SKILL_DIR, "SKILL.md"), skillMd);
console.log("Generated SKILL.md");

// --- Generate docs/*.md ---

fs.mkdirSync(DOCS_DIR, { recursive: true });

for (const topicId of TOPIC_IDS) {
  const chunk = DOC_CHUNKS[topicId];
  const content = `${GENERATED_COMMENT}\n# ${chunk.title}\n\n${chunk.content}\n`;
  fs.writeFileSync(path.join(DOCS_DIR, `${topicId}.md`), content);
}

console.log(`Generated ${TOPIC_IDS.length} doc files in docs/`);
